name: Verify Proof with Coq and Z3

on:
  push:

jobs:
  verify_proof:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Z3, Coq, and SMTCoq
      run: |
        sudo apt update
        sudo apt install -y z3 coq opam
        opam init -y
        opam repo add coq-released https://coq.inria.fr/opam/released
        opam install coq -y
        git clone https://github.com/SMTCoq/smtcoq.git
        cd smtcoq
        sudo make install
        cd ..

    - name: Run Python script to generate SMT-LIB
      run: |
        python3 -m pip install --upgrade pip
        pip install z3-solver

        # Run the Python script (assuming the script is called `test_z3.py`)
        python3 test_z3.py
        mv *.smt2 output.smt2

    - name: Create Coq file for SMTCoq
      run: |
        echo "From SMTCoq Require Import SMTCoq." > verify.v
        echo "Goal True." >> verify.v
        echo "Proof." >> verify.v
        echo "  SMTCoq.run \"output.smt2\"." >> verify.v
        echo "  exact I." >> verify.v
        echo "Qed." >> verify.v

    - name: Run Coq with SMTCoq
      run: |
        coqtop -batch -use-native-compiler verify.v
