name: Python tests

on:
  push:
    paths:
    - 'code/**'
    - '.github/workflows/python.yml'
  schedule:
  - cron: "0 0 1 * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  python:
    strategy:
      fail-fast: false
      matrix:
        selection:
        - lint
        - base_2
        - base_2_12
        - base_n_2
        - base_n_3
        - base_n_4
        - base_n_5
        - base_n_6
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
        cache: 'pip'
        cache-dependency-path: requirements.txt

    - name: Fetch test dependencies
      run: python -m pip install -r requirements.txt

    - name: Run tests (${{matrix.selection}})
      run: |
        ulimit -S -v 14680064; ulimit -H -v; ulimit -S -v
        ulimit -S -m 14680064; ulimit -H -m; ulimit -S -m
        pytest_args=()
        case ${{matrix.selection}} in
          lint)
            pytest_args+=(--isort --flake8 --mypy --mypy-ignore-missing-imports -k "not test_compare")
            test_len=0
            ;;
          base_2)
            test_len=29
            pytest_args+=(-k "test_compare_2_1 and not 2_12" --maxfail=2)
            ;;
          base_2_12)
            test_len=17
            pytest_args+=(-k "2_12" --timeout=21585)
            ;;
          *)
            IFS='_' read -r prefix1 prefix2 definition <<< "${{matrix.selection}}"
            case $((definition)) in
              2|4|5|6)
                test_len=30
                ;;
              3)
                test_len=29
                ;;
              *)
                echo "Unknown definition; limit not set"
                exit -1
                ;;
            esac
            pytest_args=(-k "test_compare_n_1_to_n[$definition-" --maxfail=2)
            ;;
        esac
        echo "Testing up to 2^$test_len"
        sed -i "s/^test_len = .*/test_len = 2**$test_len/" code/test_seq.py
        echo "${pytest_args[@]}"
        python -m pytest "${pytest_args[@]}"
