name: Python tests

on:
  push:
    paths:
    - 'code/**'
    - '.github/workflows/python.yml'
  schedule:
  - cron: "0 0 1 * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Use Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
        cache: 'pip'
        cache-dependency-path: requirements.txt

    - name: Fetch test dependencies
      run: python -m pip install -r requirements.txt

    - name: Run Linters
      run: python -m pytest --isort --flake8 --mypy --mypy-ignore-missing-imports -k "not test_compare"

  base_2:
    strategy:
      fail-fast: false
      matrix:
        def: [2_02, 2_03, 2_04, 2_05, 2_06, 2_07, 2_08, 2_09, 2_10, 2_11, 2_12, 2_13, n_01, n_02, n_03, n_04, n_05, n_06]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Use Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
        cache: 'pip'
        cache-dependency-path: requirements.txt

    - name: Fetch test dependencies
      run: python -m pip install -r requirements.txt

    - name: Run tests (${{matrix.def}})
      run: |
        ulimit -S -v 14680064; ulimit -H -v; ulimit -S -v
        ulimit -S -m 14680064; ulimit -H -m; ulimit -S -m
        case ${{matrix.def}} in
          2_04)
            test_len=36
            ;;
          2_0[23])
            test_len=35
            ;;
          2_0[689]|2_1[01])
            test_len=34
            ;;
          n_01)
            test_len=33
            ;;
          n_0[23]|[2n]_05)
            test_len=32
            ;;
          n_06)
            test_len=31
            ;;
          n_04|2_07|2_13)
            test_len=29
            ;;
          2_12)
            test_len=16
            ;;
          *)
            echo "Unknown definition; limit not set"
            exit -1
            ;;
        esac
        sed -i "s/^test_len = .*/test_len = 2**$test_len/" code/test_seq.py
        echo "Testing up to 2^$test_len"
        python -m pytest -k "${{matrix.def}}" --timeout=21555

  base_n:
    strategy:
      fail-fast: false
      matrix:
        def: [2, 3, 4, 5, 6]
        base: [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
        cache: 'pip'
        cache-dependency-path: requirements.txt

    - name: Fetch test dependencies
      run: python -m pip install -r requirements.txt

    - name: Run tests (${{matrix.def}} ${{matrix.base}})
      run: |
        ulimit -S -v 14680064; ulimit -H -v; ulimit -S -v
        ulimit -S -m 14680064; ulimit -H -m; ulimit -S -m
        case ${{matrix.def}}-${{matrix.base}} in
          [234]-*)
            test_len=29
            ;;
          [56]-*)
            test_len=30
            ;;
          *)
            echo "Unknown definition; limit not set"
            exit -1
            ;;
        esac
        echo "Testing up to 2^$test_len"
        sed -i "s/^test_len = .*/test_len = 2**$test_len/" code/test_seq.py
        python -m pytest -k "${{matrix.def}}-base_${{matrix.base}}" --timeout=21555
